### ISSUE TITLE
当语雀文档的标题包含空格和回车时，执行导出时会提示该文档写入失败

### ISSUE THREAD

**Issue by wsy1074** [Ri0nGo/ScriptCode#1]
首先非常感谢，语雀不能导出的问题困扰我很久了，这款工具很好用。但是当语雀文档的标题包含空格和回车时，执行导出时会提示该文档写入失败，电脑小白，不太清楚怎么处理代码，麻烦大佬帮忙看看。

**Comment by Ri0nGo** [comment]
你好，当文档标题含空格时，我这边测试是可以正常导出的，你能展示一下错误截图以及报错的语雀文档标题格式截图吗

**Comment by wsy1074** [comment]
包含空格和回车，也就是标题有换行
![image](https://user-images.githubusercontent.com/94664661/201524675-3c1df6b5-2c82-4c0a-9b37-138c5fd68d4d.png)

![image](https://user-images.githubusercontent.com/94664661/201524686-16b092f0-c7ae-4c88-8e86-97e0cbd72c56.png)

**Comment by wsy1074** [comment]
> 你好，当文档标题含空格时，我这边测试是可以正常导出的，你能展示一下错误截图以及报错的语雀文档标题格式截图吗

尝试了一下，发现是Windows系统不支持创建这样的文件名，会报错。如下图
![image](https://user-images.githubusercontent.com/94664661/201525157-95d08222-39f6-4c74-be1e-890a56b30a10.png)

大佬帮忙看看有什么解决办法吗？

**Comment by Ri0nGo** [comment]
你好，这是Windows系统对文件的命名要求，不能对系统层面进行修改，只能把不包含的字符去掉。

**Comment by wsy1074** [comment]
> 你好，这是Windows系统对文件的命名要求，不能对系统层面进行修改，只能把不包含的字符去掉。

能否在生成文件名时检测并自动替换掉这些字符？

**Comment by Ri0nGo** [comment]
可以的，我提交一个版本

**Comment by Ri0nGo** [comment]
你好，我提交了一个版本你测试一下。

**Comment by wsy1074** [comment]
![image](https://user-images.githubusercontent.com/94664661/201526695-3fce525e-c01f-4ff8-a0d0-ca01853fc099.png)
![image](https://user-images.githubusercontent.com/94664661/201526707-e8ca31f1-150d-405e-84e6-415e4e38e06a.png)
嗯，文章都可以顺利导出了，谢谢大佬
如果能标记出修改了哪些文件的文件名就更好了

**Comment by wsy1074** [comment]
我稍后再学习一下这个代码，看看能不能看懂，主要是想自己修改一下，导出特定的知识库和文章，因为有时候不需要全部导出

**Comment by Ri0nGo** [comment]
好的，感谢您提的issue

**Comment by Ri0nGo** [comment]
已处理
